WORDS = [
  ['Hello', 'nǐ hǎo'],
  ['World', 'shì jiè'],
  ['Friend', 'péng yǒu'],
  ['Family', 'jiā tíng'],
  ['Love', 'ài'],
  ['Peace', 'hé píng'],
  ['Happy', 'kuài lè'],
  ['Sad', 'bēi shāng'],
  ['Sun', 'tài yáng'],
  ['Moon', 'yuè liàng'],
  ['Star', 'xīng xīng'],
  ['Sky', 'tiān kōng'],
  ['Weak', 'ruò'],
  ['Clean', 'gān jìng'],
  ['Dirty', 'zāng'],
  ['Happy', 'gāo xìng'],
  ['Angry', 'shēng qì'],
  ['Hungry', 'è'],

  ['Thirsty', 'kě'],
  ['Tired', 'lèi'],
  ['Healthy', 'jiàn kāng'],
  ['Sick', 'shēng bìng'],
  ['Beautiful', 'měi lì'],
  ['Ugly', 'chǒu'],
  ['Rich', 'fù'],
  ['Poor', 'qióng'],
  ['Easy', 'róng yì'],
  ['Difficult', 'kùn nán']
]